### DISCUSSION TITLE
Hyperparameter suggestions considering the speed in lammps

### DISCUSSION THREAD

**Discussion by Hongyu-yu** [mir-group/allegro#26] [Q&A] [answered]
To reach a good balance of accuracy and efficiency in MD, is there any advice?
As illustrated in the allegro paper, a very small net is used with one layer to reach high speed in MD.
For general config such as [configs/example.yaml](https://github.com/mir-group/allegro/blob/c56bc809b689e60486ea30ef6eba5267430a147b/configs/example.yaml), it suggests a large net however way slower than the speed in the paper.
It seems that following hyperparameters are the most important:  r_max, num_layers, l_max, env_embed_multiplicity, two_body_latent_mlp_latent_dimensions, latent_mlp_latent_dimensions, edge_eng_mlp_latent_dimensions
I usually use:
```yaml
num_layers: 2
l_max: 2
parity: o3_full
env_embed_multiplicity: 16
two_body_latent_mlp_latent_dimensions: [32, 64, 128]
latent_mlp_latent_dimensions: [128]
edge_eng_mlp_latent_dimensions: [128, 64]
```
which is much smaller than [configs/example.yaml](https://github.com/mir-group/allegro/blob/c56bc809b689e60486ea30ef6eba5267430a147b/configs/example.yaml) and end up with 0.368 ns/day with 7680 atoms on 4 GPUs without Kokko as our server doesn't support:( 
Is there any advice or idea for a better speed? Thanks!
