### DISCUSSION TITLE
Training for 2D materials

### DISCUSSION THREAD

**Discussion by rick9402** [mir-group/allegro#38] [Q&A]
I am currently working on using Allegro for training ML force fields for 2D materials. However, after training four models with an increasing number of training samples (1k, 2k, 4k, 8k, total dataset contains 10k), I don't see any considerable reduction in the MAE for energies and forces, as I observed when I reproduced the calculations for LiPS system. Therefore, I would like to know whether Allegro/NequIP works for training on 2D materials or, maybe, I need to consider an additional flag when investigating 2D systems. 

In addition, I would like to ask whether NequIP/Allegro can use parallelisation on GPUs. If it is possible, please, could you tell me how to activate the training on multiple GPUs on the same GPU-node? I tried modifying the batch script in our cluster but it didn't work.

Finally, my third and last question is how to set up the training file for periodic systems, since so far I have been working with an npz file instead of xyz. This is because when setting up with an npz file I have the opportunity to put the key mapping "cell", while on xyz I have not been able to do so.

```
dataset_file_name: Periodic.npz                                                    # path to data set file
key_mapping:
  z: atomic_numbers                                                                # atomic species, integers
  E: total_energy                                                                  # total potential eneriges to train to
  F: forces                                                                        # atomic forces to train to
  R: pos                                                                           # raw atomic positions
  lattice: cell
npz_fixed_field_keys:                                                              # fields that are repeated across different examples
  - atomic_numbers

chemical_symbol_to_type:
  H: 0
  C: 1
  N: 2
```
